<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <PlatformTarget>x64</PlatformTarget>
        <Prefer32Bit>false</Prefer32Bit>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Atomcraft">
            <HintPath>$(GameInstallDir)\data_Atomcraft_windows_x86_64\Atomcraft.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="GodotSharp">
            <HintPath>$(GameInstallDir)\data_Atomcraft_windows_x86_64\GodotSharp.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Newtonsoft.Json">
            <HintPath>$(GameInstallDir)\data_Atomcraft_windows_x86_64\Newtonsoft.Json.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="GodotMonoModLoader">
            <HintPath>$(GameInstallDir)\GodotMonoModLoader\GodotMonoModLoader.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <PackageReference Include="Godot.SourceGenerators" Version="4.4.0" >
            <OutputItemType>Analyzer</OutputItemType>
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
        </PackageReference>
        <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    </ItemGroup>

    <PropertyGroup>
        <GodotProjectDir>$(MSBuildProjectDirectory)</GodotProjectDir>
        <GodotTargetPlatform>Windows</GodotTargetPlatform>
        <GodotPlatform>Windows</GodotPlatform>
        <GodotTargetArchitecture>x86_64</GodotTargetArchitecture>
        <GodotApiConfiguration>Release</GodotApiConfiguration>
        <GodotRealTIsDouble>false</GodotRealTIsDouble>
        <EnableGodotGenerators>true</EnableGodotGenerators>
    </PropertyGroup>

    <ItemGroup>
        <CompilerVisibleProperty Include="GodotProjectDir" />
        <CompilerVisibleProperty Include="GodotTargetPlatform" />
        <CompilerVisibleProperty Include="GodotPlatform" />
        <CompilerVisibleProperty Include="GodotTargetArchitecture" />
        <CompilerVisibleProperty Include="GodotApiConfiguration" />
        <CompilerVisibleProperty Include="GodotRealTIsDouble" />
        <CompilerVisibleProperty Include="EnableGodotGenerators" />
    </ItemGroup>
    
    
    <PropertyGroup>
        <ResourcesDir>$(ProjectDir)Resources</ResourcesDir>
    </PropertyGroup>
    <ItemGroup>
        <Resources Include="$(ResourcesDir)\**\*" />
    </ItemGroup>



    <Target Name="CreateModZip" AfterTargets="Build">

        <PropertyGroup>
            <ModName>$(ProjectName)</ModName>
            <ModDir>$(TargetDir)$(ModName)</ModDir>
            <ModZip>$(ProjectDir)../Release/$(ModName).zip</ModZip>
        </PropertyGroup>

        <RemoveDir Directories="$(ModDir)" />

        <MakeDir Directories="$(ModDir)" />

        <Copy
                SourceFiles="$(TargetPath)"
                DestinationFolder="$(ModDir)/$(ModName)" />

        <Copy   Condition="Exists($(ResourcesDir))"
                SourceFiles="@(Resources)"
                DestinationFiles="@(Resources->'$(ModDir)/$(ModName)/Resources/%(RecursiveDir)%(Filename)%(Extension)')"/>

        <Copy
                SourceFiles="$(ProjectDir)mod.json"
                DestinationFolder="$(ModDir)/$(ModName)" />

        <Delete Files="$(ModZip)" />

        <ZipDirectory
                SourceDirectory="$(ModDir)"
                DestinationFile="$(ModZip)"
                Overwrite="true" />

        <RemoveDir Directories="$(ModDir)" />

        <Message
                Importance="high"
                Text="Mod ZIP created: $(ModZip)" />

    </Target>

    <Target Name="InstallModZip" AfterTargets="Build" DependsOnTargets="CreateModZip">

        <PropertyGroup>
            <InstallDir>$(AppData)/Godot/app_userdata/Atomcraft/Mods</InstallDir>
        </PropertyGroup>

        <Delete Files="$(InstallDir)/$(ModName).zip" />

        <Copy
                SourceFiles="$(ModZip)"
                DestinationFolder="$(InstallDir)" />

        <Message
                Importance="high"
                Text="Mod ZIP installed: $(InstallDir)/$(ProjectName).zip" />

    </Target>


</Project>
